# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/danny/Documents/school/cpe400/gpu_simulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/danny/Documents/school/cpe400/gpu_simulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/danny/Documents/school/cpe400/gpu_simulator/CMakeFiles /home/danny/Documents/school/cpe400/gpu_simulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/danny/Documents/school/cpe400/gpu_simulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named ArrayList

# Build rule for target.
ArrayList: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ArrayList
.PHONY : ArrayList

# fast build rule for target.
ArrayList/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArrayList.dir/build.make CMakeFiles/ArrayList.dir/build
.PHONY : ArrayList/fast

#=============================================================================
# Target rules for targets named OffFile

# Build rule for target.
OffFile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OffFile
.PHONY : OffFile

# fast build rule for target.
OffFile/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OffFile.dir/build.make CMakeFiles/OffFile.dir/build
.PHONY : OffFile/fast

#=============================================================================
# Target rules for targets named Primitives

# Build rule for target.
Primitives: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Primitives
.PHONY : Primitives

# fast build rule for target.
Primitives/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Primitives.dir/build.make CMakeFiles/Primitives.dir/build
.PHONY : Primitives/fast

#=============================================================================
# Target rules for targets named Transformation

# Build rule for target.
Transformation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Transformation
.PHONY : Transformation

# fast build rule for target.
Transformation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Transformation.dir/build.make CMakeFiles/Transformation.dir/build
.PHONY : Transformation/fast

#=============================================================================
# Target rules for targets named Lighting

# Build rule for target.
Lighting: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Lighting
.PHONY : Lighting

# fast build rule for target.
Lighting/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lighting.dir/build.make CMakeFiles/Lighting.dir/build
.PHONY : Lighting/fast

#=============================================================================
# Target rules for targets named Projection

# Build rule for target.
Projection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Projection
.PHONY : Projection

# fast build rule for target.
Projection/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projection.dir/build.make CMakeFiles/Projection.dir/build
.PHONY : Projection/fast

#=============================================================================
# Target rules for targets named Rasterization

# Build rule for target.
Rasterization: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Rasterization
.PHONY : Rasterization

# fast build rule for target.
Rasterization/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rasterization.dir/build.make CMakeFiles/Rasterization.dir/build
.PHONY : Rasterization/fast

#=============================================================================
# Target rules for targets named PGMFile

# Build rule for target.
PGMFile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PGMFile
.PHONY : PGMFile

# fast build rule for target.
PGMFile/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PGMFile.dir/build.make CMakeFiles/PGMFile.dir/build
.PHONY : PGMFile/fast

#=============================================================================
# Target rules for targets named make_build_dir

# Build rule for target.
make_build_dir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 make_build_dir
.PHONY : make_build_dir

# fast build rule for target.
make_build_dir/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/make_build_dir.dir/build.make CMakeFiles/make_build_dir.dir/build
.PHONY : make_build_dir/fast

#=============================================================================
# Target rules for targets named clean_custom

# Build rule for target.
clean_custom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean_custom
.PHONY : clean_custom

# fast build rule for target.
clean_custom/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean_custom.dir/build.make CMakeFiles/clean_custom.dir/build
.PHONY : clean_custom/fast

ArrayList/ArrayList.o: ArrayList/ArrayList.c.o
.PHONY : ArrayList/ArrayList.o

# target to build an object file
ArrayList/ArrayList.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArrayList.dir/build.make CMakeFiles/ArrayList.dir/ArrayList/ArrayList.c.o
.PHONY : ArrayList/ArrayList.c.o

ArrayList/ArrayList.i: ArrayList/ArrayList.c.i
.PHONY : ArrayList/ArrayList.i

# target to preprocess a source file
ArrayList/ArrayList.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArrayList.dir/build.make CMakeFiles/ArrayList.dir/ArrayList/ArrayList.c.i
.PHONY : ArrayList/ArrayList.c.i

ArrayList/ArrayList.s: ArrayList/ArrayList.c.s
.PHONY : ArrayList/ArrayList.s

# target to generate assembly for a file
ArrayList/ArrayList.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ArrayList.dir/build.make CMakeFiles/ArrayList.dir/ArrayList/ArrayList.c.s
.PHONY : ArrayList/ArrayList.c.s

Lighting/Lighting.o: Lighting/Lighting.c.o
.PHONY : Lighting/Lighting.o

# target to build an object file
Lighting/Lighting.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lighting.dir/build.make CMakeFiles/Lighting.dir/Lighting/Lighting.c.o
.PHONY : Lighting/Lighting.c.o

Lighting/Lighting.i: Lighting/Lighting.c.i
.PHONY : Lighting/Lighting.i

# target to preprocess a source file
Lighting/Lighting.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lighting.dir/build.make CMakeFiles/Lighting.dir/Lighting/Lighting.c.i
.PHONY : Lighting/Lighting.c.i

Lighting/Lighting.s: Lighting/Lighting.c.s
.PHONY : Lighting/Lighting.s

# target to generate assembly for a file
Lighting/Lighting.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lighting.dir/build.make CMakeFiles/Lighting.dir/Lighting/Lighting.c.s
.PHONY : Lighting/Lighting.c.s

OffFile/OffFile.o: OffFile/OffFile.c.o
.PHONY : OffFile/OffFile.o

# target to build an object file
OffFile/OffFile.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OffFile.dir/build.make CMakeFiles/OffFile.dir/OffFile/OffFile.c.o
.PHONY : OffFile/OffFile.c.o

OffFile/OffFile.i: OffFile/OffFile.c.i
.PHONY : OffFile/OffFile.i

# target to preprocess a source file
OffFile/OffFile.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OffFile.dir/build.make CMakeFiles/OffFile.dir/OffFile/OffFile.c.i
.PHONY : OffFile/OffFile.c.i

OffFile/OffFile.s: OffFile/OffFile.c.s
.PHONY : OffFile/OffFile.s

# target to generate assembly for a file
OffFile/OffFile.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OffFile.dir/build.make CMakeFiles/OffFile.dir/OffFile/OffFile.c.s
.PHONY : OffFile/OffFile.c.s

PGMFile/PGMFile.o: PGMFile/PGMFile.c.o
.PHONY : PGMFile/PGMFile.o

# target to build an object file
PGMFile/PGMFile.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PGMFile.dir/build.make CMakeFiles/PGMFile.dir/PGMFile/PGMFile.c.o
.PHONY : PGMFile/PGMFile.c.o

PGMFile/PGMFile.i: PGMFile/PGMFile.c.i
.PHONY : PGMFile/PGMFile.i

# target to preprocess a source file
PGMFile/PGMFile.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PGMFile.dir/build.make CMakeFiles/PGMFile.dir/PGMFile/PGMFile.c.i
.PHONY : PGMFile/PGMFile.c.i

PGMFile/PGMFile.s: PGMFile/PGMFile.c.s
.PHONY : PGMFile/PGMFile.s

# target to generate assembly for a file
PGMFile/PGMFile.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PGMFile.dir/build.make CMakeFiles/PGMFile.dir/PGMFile/PGMFile.c.s
.PHONY : PGMFile/PGMFile.c.s

Primitives/Primitives.o: Primitives/Primitives.c.o
.PHONY : Primitives/Primitives.o

# target to build an object file
Primitives/Primitives.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Primitives.dir/build.make CMakeFiles/Primitives.dir/Primitives/Primitives.c.o
.PHONY : Primitives/Primitives.c.o

Primitives/Primitives.i: Primitives/Primitives.c.i
.PHONY : Primitives/Primitives.i

# target to preprocess a source file
Primitives/Primitives.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Primitives.dir/build.make CMakeFiles/Primitives.dir/Primitives/Primitives.c.i
.PHONY : Primitives/Primitives.c.i

Primitives/Primitives.s: Primitives/Primitives.c.s
.PHONY : Primitives/Primitives.s

# target to generate assembly for a file
Primitives/Primitives.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Primitives.dir/build.make CMakeFiles/Primitives.dir/Primitives/Primitives.c.s
.PHONY : Primitives/Primitives.c.s

Projection/Projection.o: Projection/Projection.c.o
.PHONY : Projection/Projection.o

# target to build an object file
Projection/Projection.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projection.dir/build.make CMakeFiles/Projection.dir/Projection/Projection.c.o
.PHONY : Projection/Projection.c.o

Projection/Projection.i: Projection/Projection.c.i
.PHONY : Projection/Projection.i

# target to preprocess a source file
Projection/Projection.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projection.dir/build.make CMakeFiles/Projection.dir/Projection/Projection.c.i
.PHONY : Projection/Projection.c.i

Projection/Projection.s: Projection/Projection.c.s
.PHONY : Projection/Projection.s

# target to generate assembly for a file
Projection/Projection.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Projection.dir/build.make CMakeFiles/Projection.dir/Projection/Projection.c.s
.PHONY : Projection/Projection.c.s

Rasterization/Rasterization.o: Rasterization/Rasterization.c.o
.PHONY : Rasterization/Rasterization.o

# target to build an object file
Rasterization/Rasterization.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rasterization.dir/build.make CMakeFiles/Rasterization.dir/Rasterization/Rasterization.c.o
.PHONY : Rasterization/Rasterization.c.o

Rasterization/Rasterization.i: Rasterization/Rasterization.c.i
.PHONY : Rasterization/Rasterization.i

# target to preprocess a source file
Rasterization/Rasterization.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rasterization.dir/build.make CMakeFiles/Rasterization.dir/Rasterization/Rasterization.c.i
.PHONY : Rasterization/Rasterization.c.i

Rasterization/Rasterization.s: Rasterization/Rasterization.c.s
.PHONY : Rasterization/Rasterization.s

# target to generate assembly for a file
Rasterization/Rasterization.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rasterization.dir/build.make CMakeFiles/Rasterization.dir/Rasterization/Rasterization.c.s
.PHONY : Rasterization/Rasterization.c.s

Transformation/Transformation.o: Transformation/Transformation.c.o
.PHONY : Transformation/Transformation.o

# target to build an object file
Transformation/Transformation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Transformation.dir/build.make CMakeFiles/Transformation.dir/Transformation/Transformation.c.o
.PHONY : Transformation/Transformation.c.o

Transformation/Transformation.i: Transformation/Transformation.c.i
.PHONY : Transformation/Transformation.i

# target to preprocess a source file
Transformation/Transformation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Transformation.dir/build.make CMakeFiles/Transformation.dir/Transformation/Transformation.c.i
.PHONY : Transformation/Transformation.c.i

Transformation/Transformation.s: Transformation/Transformation.c.s
.PHONY : Transformation/Transformation.s

# target to generate assembly for a file
Transformation/Transformation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Transformation.dir/build.make CMakeFiles/Transformation.dir/Transformation/Transformation.c.s
.PHONY : Transformation/Transformation.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... clean_custom"
	@echo "... make_build_dir"
	@echo "... ArrayList"
	@echo "... Lighting"
	@echo "... OffFile"
	@echo "... PGMFile"
	@echo "... Primitives"
	@echo "... Projection"
	@echo "... Rasterization"
	@echo "... Transformation"
	@echo "... main"
	@echo "... ArrayList/ArrayList.o"
	@echo "... ArrayList/ArrayList.i"
	@echo "... ArrayList/ArrayList.s"
	@echo "... Lighting/Lighting.o"
	@echo "... Lighting/Lighting.i"
	@echo "... Lighting/Lighting.s"
	@echo "... OffFile/OffFile.o"
	@echo "... OffFile/OffFile.i"
	@echo "... OffFile/OffFile.s"
	@echo "... PGMFile/PGMFile.o"
	@echo "... PGMFile/PGMFile.i"
	@echo "... PGMFile/PGMFile.s"
	@echo "... Primitives/Primitives.o"
	@echo "... Primitives/Primitives.i"
	@echo "... Primitives/Primitives.s"
	@echo "... Projection/Projection.o"
	@echo "... Projection/Projection.i"
	@echo "... Projection/Projection.s"
	@echo "... Rasterization/Rasterization.o"
	@echo "... Rasterization/Rasterization.i"
	@echo "... Rasterization/Rasterization.s"
	@echo "... Transformation/Transformation.o"
	@echo "... Transformation/Transformation.i"
	@echo "... Transformation/Transformation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

